require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'flowline.gemspec'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'flowline.gemspec'

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Naming/MethodParameterName:
  Exclude:
    - 'spec/**/*'

RSpec/SpecFilePathFormat:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/flowline/step_retry_spec.rb'
    - 'spec/flowline/step_timeout_spec.rb'
